name: tork-ros-roomblock
version: '0.1'
summary: Roomblock snap package
description: |
  This is Roomblock snap package.

grade: stable
confinement: devmode

parts:
  workspace:
    plugin: catkin
    rosdistro: kinetic
    rosinstall-files: [roomblock.rosinstall]
    catkin-packages: [roomblock_bringup, roomblock_description]

apps:
  launch:
    command: roslaunch roomblock_bringup roomblock.launch --screen
    daemon: simple
    plugs: [network, network-bind]
