name: tork-ros-roomblock
version: '0.1'
summary: Roomblock snap package
description: |
  This is Roomblock snap package.

grade: stable
confinement: devmode

# Workaround for LP: #1677002.
build-packages: [lsb-release]

parts:
  workspace:
    plugin: catkin
    rosdistro: kinetic
    source: .
    source-space: .
    catkin-packages: [roomblock_bringup, roomblock_description]

apps:
  launch:
    command: roslaunch roomblock_bringup roomblock.launch --screen
    daemon: simple
    plugs: [network, network-bind]
