name: tork-ros-roomblock
version: '0.1'
summary: Roomblock snap package
description: |
  This is Roomblock snap package.

grade: stable
confinement: devmode

architectures: [armhf]

parts:
  workspace:
    plugin: catkin
    rosdistro: kinetic
    catkin-packages: [roomblock_bringup, roomblock_description]

apps:
  system:
    command: roslaunch roomblock_bringup roomblock.launch --screen
    plugs: [network, network-bind]
    daemon: simple
